%initializeTracks (self-explanatory)
% Elias Scheer
% 1-12-16
% borrowed from multipleObjectTracking example
function [tracks,tracksThatLeft] = initializeTracks_wholevideo2()
% create an empty array of tracks
tracks = struct(...
    'id', {}, ...
    'x_shift',{},...
    'y_shift',{},...
    'centroid', {}, ...
    'bbox', {}, ...
    'cropworm',{}, ...
    'cropworm_orig',{},...
    'spline',{},...
    'omega',{},...
    'end1',{},...
    'end2',{},...
    'end1_g',{},...
    'end2_g',{},...
    'curvature',{},...
    'posture_angle',{},...
    'kalmanFilter', {}, ...
    'age', {}, ...
    'totalVisibleCount', {}, ...
    'consecutiveInvisibleCount', {}, ...
    'framesActive', {},...
    'videoname',{},...
    'videoframe',{});

tracksThatLeft = struct(...
    'id', {}, ...
    'x_shift',{},...
    'y_shift',{},...
    'centroid', {}, ...
    'bbox', {}, ...
    'cropworm',{}, ...
    'cropworm_orig',{},...
    'spline',{},...
    'omega',{},...
    'end1',{},...
    'end2',{},...
    'end1_g',{},...
    'end2_g',{},...
    'curvature',{},...
    'posture_angle',{},...
    'kalmanFilter', {}, ...
    'age', {}, ...
    'totalVisibleCount', {}, ...
    'consecutiveInvisibleCount', {}, ...
    'framesActive', {},...
    'videoname',{},...
    'videoframe',{});
end


