%initializeTracks (self-explanatory)
% Elias Scheer
% 1-12-16
% borrowed from multipleObjectTracking example
function [tracks,tracksThatLeft] = initializeTracks_wholevideo()
% create an empty array of tracks
tracks = struct(...
    'id', {}, ...
    'centroid', {}, ...
    'bbox', {}, ...
    'kalmanFilter', {}, ...
    'age', {}, ...
    'totalVisibleCount', {}, ...
    'consecutiveInvisibleCount', {}, ...
    'framesActive', {} );

tracksThatLeft = struct(...
    'id', {}, ...
    'centroid', {}, ...
    'bbox', {}, ...
    'kalmanFilter', {}, ...
    'age', {}, ...
    'totalVisibleCount', {}, ...
    'consecutiveInvisibleCount', {}, ...
    'framesActive', {} );
end


